Revert xunit to post build step and use try catch to catch failures
Build step of xunit seems to be deprecated.

diff --git a/tools/jenkins/Jenkinsfile b/tools/jenkins/Jenkinsfile
--- a/tools/jenkins/Jenkinsfile
+++ b/tools/jenkins/Jenkinsfile
@@ -48,12 +48,24 @@ pipeline {
                            steps {
                                echo 'test'
                                sh 'less test.txt'
-                               xunit (
-                                thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
-                                tools: [ CTest(pattern: 'tools/jenkins/Test.xml', stopProcessingIfError: true) ]
-                                )
                            }
                        }
+                    }
+                    post {
+                        always{
+                            //TODO evaluate if it makes sense to ignore some test results (e.g. mark them optional)
+                            try {
+                                xunit (
+                                    thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
+                                    tools: [ CTest(pattern: 'tools/jenkins/Test.xml', stopProcessingIfError: true) ]
+                                )
+                            }
+                            catch (exc) {
+                                echo 'Tests failed!'
+                                sh 'exit 1'
+                                throw
+                            }
+                        }
                     }
                 }
                 stage('PyOpenMS') {
@@ -72,11 +84,22 @@ pipeline {
                                echo 'test'
                                sh 'less test.txt'
                            }
-                           xunit (
-                                thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
-                                tools: [ CTest(pattern: 'tools/jenkins/Test.xml', stopProcessingIfError: true) ]
-                           )
                        }
+                    }
+                    post {
+                        always{
+                            try {
+                                xunit (
+                                    thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
+                                    tools: [ CTest(pattern: 'tools/jenkins/Test.xml', stopProcessingIfError: true) ]
+                                )
+                            }
+                            catch (exc) {
+                                echo 'Tests failed!'
+                                sh 'exit 1'
+                                throw
+                            }
+                        }
                     }
                 }
             }
