restricted run-time of tests (default is 60 CPU seconds). set environment variable  OPENMS_TESTTIMEOUT to what you feel appropriate. The test program is simply killed (no cleanup of tmp files etc).
git-svn-id: https://open-ms.svn.sourceforge.net/svnroot/open-ms/OpenMS@2605 6adb6e08-d915-0410-941f-83917bcadc18

diff --git a/source/TEST/runtests b/source/TEST/runtests
--- a/source/TEST/runtests
+++ b/source/TEST/runtests
@@ -105,10 +105,17 @@ for i in $* ; do
 	# remove potential log files
 	rm $i.log 2>/dev/null
 
-	# run it and examine its return value
-	if ./$i > $i.output 2>&1 ; then
+	# run it
+	./$i > $i.output 2>&1
+	
+	# ... and examine its return value
+	RETVAL=`echo $?`
+	if test "$RETVAL" = "0"; then
 		# test passed - OK
 		echo "OK"
+	elif test "$RETVAL" = "24" -o "$RETVAL" = "154"; then
+		# test timed out (SIGXCPU signal ~ 24 (MinGW) ~ 128+24=154 (Linux) )
+		echo "TIMEOUT"	
 	else 
 		# test didn't pass
 		OK=false
