added File::getUniqueName; needs new configure run (QtNetwork added)
git-svn-id: https://open-ms.svn.sourceforge.net/svnroot/open-ms/OpenMS@2102 6adb6e08-d915-0410-941f-83917bcadc18

diff --git a/source/configure b/source/configure
--- a/source/configure
+++ b/source/configure
@@ -4755,7 +4755,7 @@ echo "${ECHO_T}yes" >&6
     DYNAROPTS="${DYNAROPTS} -G -fPIC -o"
   else
     if test "${OS}" == Darwin ; then
-	    DYNAROPTS="${DYNAROPTS} -single_module -framework QtSql -framework QtCore -framework OpenGL -framework QtGui -framework QtOpenGl -L${OPENMS_PATH}/contrib/lib -lxerces-c -lnetcdf -lnetcdf_c++ -lCGAL -lgsl -lsvm.o ${OPENMS_PATH}/contrib/lib/ms10lib.a -dynamiclib -fPIC -o"
+	    DYNAROPTS="${DYNAROPTS} -single_module -framework QtSql -framework QtCore -framework OpenGL -framework QtGui -framework QtOpenGl -framework QtNetwork -L${OPENMS_PATH}/contrib/lib -lxerces-c -lnetcdf -lnetcdf_c++ -lCGAL -lgsl -lsvm.o ${OPENMS_PATH}/contrib/lib/ms10lib.a -dynamiclib -fPIC -o"
 		else
   	  DYNAROPTS="${DYNAROPTS} -shared -fPIC -o"
 		fi
@@ -20368,7 +20368,8 @@ fi
 
 if test "${OS}" = "Darwin" ; then
 	QT_PLATFORM="Qt-Darwin"
-	QT_LIBOPTS="-framework QtCore -framework QtGui -framework QtSql -framework QtOpenGL"
+	QT_LIBOPTS="-framework QtCore -framework QtGui -framework QtSql -framework QtOpenGL -framework QtNetwork"
+
 else
 	echo "$as_me:$LINENO: checking for Qt headers" >&5
 echo $ECHO_N "checking for Qt headers... $ECHO_C" >&6
@@ -20948,6 +20949,63 @@ echo "$as_me: error: Aborted." >&2;}
     fi
   fi
 
+  echo "$as_me:$LINENO: checking for libQtNetwork" >&5
+echo $ECHO_N "checking for libQtNetwork... $ECHO_C" >&6
+  if test "${QT_LIBPATH}" != "" ; then
+    if test -a "${QT_LIBPATH}/libQtNetwork.so" ; then
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+      echo "$as_me:$LINENO: result: (not found!)" >&5
+echo "${ECHO_T}(not found!)" >&6
+      echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+      echo "$as_me:$LINENO: result: The QtNetwork library could not be found. Please specify the path to libqt" >&5
+echo "${ECHO_T}The QtNetwork library could not be found. Please specify the path to libqt" >&6
+      echo "$as_me:$LINENO: result: by passing the option --with-qt-libs=DIR to configure." >&5
+echo "${ECHO_T}by passing the option --with-qt-libs=DIR to configure." >&6
+      echo "$as_me:$LINENO: result: The QT package can be found under the following URL:" >&5
+echo "${ECHO_T}The QT package can be found under the following URL:" >&6
+      echo "$as_me:$LINENO: result: http://www.troll.no/qt" >&5
+echo "${ECHO_T}http://www.troll.no/qt" >&6
+      echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+      echo "$as_me:$LINENO: result: Note: OpenMS requires QT 4.x! QT3 is no longer supported." >&5
+echo "${ECHO_T}Note: OpenMS requires QT 4.x! QT3 is no longer supported." >&6
+
+	echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+	echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6
+	echo "$as_me:$LINENO: result: of the above error message, please contact the OPENMS mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the OPENMS mailing list" >&6
+	echo "$as_me:$LINENO: result: or the OPENMS developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the OPENMS developers. Please enclose the file 'conf.diag.tar'" >&6
+	echo "$as_me:$LINENO: result: which has been created in OPENMS/source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in OPENMS/source. It contains the relevant" >&6
+	echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6
+	echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6
+	echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6
+	echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6
+	echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+  tar cf $TARFILE configure configure.ac aclocal.m4 config.log
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+    fi
+  fi
+
+
 
 				if test "${QT_INCPATH}" != /usr/include && test "${QT_INCPATH}" != "" ; then
 		OPENMS_INCLUDES="${OPENMS_INCLUDES} -I${QT_INCPATH}"
@@ -20956,7 +21014,7 @@ echo "$as_me: error: Aborted." >&2;}
 				if test "${QT_LIBPATH}" != /usr/lib && test "${QT_LIBPATH}" != "" ; then
 		OPENMS_LIBS="${OPENMS_LIBS} -L${QT_LIBPATH}"
 	fi
-	OPENMS_LIBS="${OPENMS_LIBS} -lQtCore -lQtSql"
+	OPENMS_LIBS="${OPENMS_LIBS} -lQtCore -lQtSql -lQtNetwork"
 fi
 
 
@@ -21831,7 +21889,7 @@ echo "${ECHO_T}yes" >&6
 echo $ECHO_N "checking linking against QtOpenGL lib... $ECHO_C" >&6
 
 		if test "${QT_PLATFORM}" != "Qt-Darwin"; then
-			LIBS="-ltGui -lQtOpenGL ${X11_LIBOPTS} ${LIBS} ${GUI_INCLUDES}"
+			LIBS="-lQtGui -lQtOpenGL ${X11_LIBOPTS} ${LIBS} ${GUI_INCLUDES}"
 		fi
 
 		QT_LINKING_OK=0
@@ -21936,7 +21994,7 @@ echo "${ECHO_T}yes" >&6
 echo $ECHO_N "checking linking against QtSql lib... $ECHO_C" >&6
 
 		if test "${QT_PLATFORM}" != "Qt-Darwin"; then
-			LIBS="${X11_LIBOPTS} ${LIBS} ${GUI_INCLUDES}"
+			LIBS="-lQtSql ${X11_LIBOPTS} ${LIBS} ${GUI_INCLUDES}"
 		fi
 
 		QT_LINKING_OK=0
@@ -22035,6 +22093,113 @@ echo "$as_me: error: Aborted." >&2;}
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
     fi
+
+
+
+                echo "$as_me:$LINENO: checking linking against QtNetwork lib" >&5
+echo $ECHO_N "checking linking against QtNetwork lib... $ECHO_C" >&6
+
+    if test "${QT_PLATFORM}" != "Qt-Darwin"; then
+      LIBS="-lQtNetwork ${X11_LIBOPTS} ${LIBS} ${GUI_INCLUDES}"
+    fi
+
+    QT_LINKING_OK=0
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <QtNetwork/QHostInfo>
+int
+main ()
+{
+QHostInfo host_info;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  QT_LINKING_OK=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+    if test "${QT_LINKING_OK+set}" != set ; then
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+      echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+      echo "$as_me:$LINENO: result: Cannot link against QtNetwork!" >&5
+echo "${ECHO_T}Cannot link against QtNetwork!" >&6
+      echo "$as_me:$LINENO: result: If Qt4 is installed, please specify the path to the library" >&5
+echo "${ECHO_T}If Qt4 is installed, please specify the path to the library" >&6
+      echo "$as_me:$LINENO: result: using the option --with-qt-libs=DIR" >&5
+echo "${ECHO_T}using the option --with-qt-libs=DIR" >&6
+      echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+      echo "$as_me:$LINENO: result: Another possible reason is threading support. Have a look at the OpenMS installation documentation!" >&5
+echo "${ECHO_T}Another possible reason is threading support. Have a look at the OpenMS installation documentation!" >&6
+
+	echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+	echo "$as_me:$LINENO: result: Configure failed. If you cannot solve your problem with the aid" >&5
+echo "${ECHO_T}Configure failed. If you cannot solve your problem with the aid" >&6
+	echo "$as_me:$LINENO: result: of the above error message, please contact the OPENMS mailing list" >&5
+echo "${ECHO_T}of the above error message, please contact the OPENMS mailing list" >&6
+	echo "$as_me:$LINENO: result: or the OPENMS developers. Please enclose the file 'conf.diag.tar'" >&5
+echo "${ECHO_T}or the OPENMS developers. Please enclose the file 'conf.diag.tar'" >&6
+	echo "$as_me:$LINENO: result: which has been created in OPENMS/source. It contains the relevant" >&5
+echo "${ECHO_T}which has been created in OPENMS/source. It contains the relevant" >&6
+	echo "$as_me:$LINENO: result: files from this configure run. In most cases, the information" >&5
+echo "${ECHO_T}files from this configure run. In most cases, the information" >&6
+	echo "$as_me:$LINENO: result: is necessary to diagnose what went wrong. This file contains" >&5
+echo "${ECHO_T}is necessary to diagnose what went wrong. This file contains" >&6
+	echo "$as_me:$LINENO: result: information about your system setup and versions of compilers" >&5
+echo "${ECHO_T}information about your system setup and versions of compilers" >&6
+	echo "$as_me:$LINENO: result: and other tools installed in your system." >&5
+echo "${ECHO_T}and other tools installed in your system." >&6
+	echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+	TARFILE=conf.diag.tar
+	if test -f $TARFILE ; then
+		${RM} $TARFILE ;
+	fi
+  tar cf $TARFILE configure configure.ac aclocal.m4 config.log
+	{ { echo "$as_me:$LINENO: error: Aborted." >&5
+echo "$as_me: error: Aborted." >&2;}
+   { (exit 1); exit 1; }; }
+
+    else
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    fi
+
 
 		if test "${QT_PLATFORM}" != "Qt-Darwin"; then
 			LIBS=${SAVE_LIBS}
