Update openms_ci_matrix_full.yml
refactor where we check inputs to avoid bash issues. Fix assignment instead of equality test in do_package. Export version number from changelog step

diff --git a/.github/workflows/openms_ci_matrix_full.yml b/.github/workflows/openms_ci_matrix_full.yml
--- a/.github/workflows/openms_ci_matrix_full.yml
+++ b/.github/workflows/openms_ci_matrix_full.yml
@@ -157,6 +157,7 @@ jobs:
           then
             VERSION_NUMBER=${VERSION_NUMBER%.*}
           fi
+          echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
           grep -ne "----[[:space:]]*OpenMS" ${{ github.workspace }}/OpenMS/CHANGELOG > index_changelog.txt 
           START=$(cat index_changelog.txt | grep -A 1 -e " $VERSION_NUMBER " | cut -f1 -d: | head -1)
           END=$(cat index_changelog.txt | grep -A 1 -e " $VERSION_NUMBER " | cut -f1 -d: | tail -1)
@@ -164,47 +165,32 @@ jobs:
           echo $START
           echo $END
           awk "NR > $START && NR < $END" OpenMS/CHANGELOG > ${{ github.workspace }}/changelog.txt
-
-          # if we are running as the result of a push rather than a PR the ${{ inputs.* }} flat out don't exist, which makes the ops checking code choke.
-          # unfortunately it looks like bash evaluates the syntax even if we never reach the code, so we need to make sure the variables exist
-
-          if [[ 'true' == ${{ github.event_name == 'push' }} ]]; then
-            DO_RELEASE = 'false'
-            KNIME = 'false'
-            PACKAGE = 'false'
-            MARK_AS_LATEST = 'false'
-            ANNOUNCE_RELEASE = 'false'
-          else
-            DO_RELEASE = ${{ inputs.do_release }}
-            KNIME = ${{ inputs.knime }}
-            PACKAGE = ${{ inputs.package }}
-            MARK_AS_LATEST = ${{ inputs.mark_as_latest }}
-            ANNOUNCE_RELEASE = ${{ inputs.announce_release }}
-          fi
-          # check if we want to be marked as latest, and if we actually should.
-          if [[ 'true' == $DO_RELEASE ]]; then
-            if [[ 'false' == $KNIME || 'false' == $PACKAGE ]]; then
-              echo "Can't do a release without building the OpenMS package and the KNIME package"
-              exit 1
-            else
-              if [[ 'true' == $MARK_AS_LATEST && "$(git tag -l $VERSION_NUMBER)" ]]; then
-                echo "Can't mark as latest, a tag with the same version already exists"
-                exit 1
-              fi
-            fi
-          else
-            if [[ 'true' == $MARK_AS_LATEST || 'true' == $ANNOUNCE_RELEASE ]]; then
-              echo "Can't mark as lates or announce release unless we do a release"
-              exit 1
-            fi
-          fi
-
-
         else
           echo "Branch name does not match the expected pattern."
           exit 1
         fi
 
+    - name: check input options
+      if: github.event_name == workflow_dispatch
+      shell: bash
+      run: |
+          # check if we want to be marked as latest, and if we actually should.
+          if [[ 'true' == ${{ inputs.do_release }} ]]; then
+            if [[ 'false' == ${{ inputs.knime }} || 'false' == ${{ inputs.package }} ]]; then
+              echo "Can't do a release without building the OpenMS package and the KNIME package"
+              exit 1
+            else
+              if [[ 'true' == ${{ inputs.mark_as_latest }} && "$(git tag -l ${{ steps.create_changelog.outputs.version_number }})" ]]; then
+                echo "Can't mark as latest, a tag with the same version already exists"
+                exit 1
+              fi
+            fi
+          else
+            if [[ 'true' == ${{ inputs.mark_as_latest }} || 'true' == ${{inputs.announce_release}} ]]; then
+              echo "Can't mark as lates or announce release unless we do a release"
+              exit 1
+            fi
+          fi
 
       
     - name: Emulate a Visual Studio shell (Windows)
@@ -559,7 +545,7 @@ jobs:
             cat > releaseTextHeader.txt << EOF
             Dear OpenMS-Users,
 
-            we are proud to announce the release of OpenMS $version. Grab it <a href="https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/$version">here</a>
+            we are proud to announce the release of OpenMS ${{ jobs.build_and_test.outputs.version_number }}. Grab it <a href="https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/${{ jobs.build_and_test.outputs.version_number }}">here</a>
 
             In the following you find all important changes to the previous version:
 
